#!/bin/bash
echo "obase=8;ibase=5;$(echo "$WATER" | tr -cd 'water' | tr 'water' '01234') + ibase=4;$(echo "$STIR" | tr -cd 'stir' | tr 'stir' '0123')" | bc | tr -d '\n' | tr '01234567' 'bestchol' && echo
